# Site settings
title: MhdAli
email: ma.alfarra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Hello IT, Did you try turn it off and on again"
  Mohammad Ali Alfarra, System Administration, Photography, Football player and amoung other things.

  Current OS: ArchLinux OS, i3 WM.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mhdali.github.io" # the base hostname & protocol for your site
twitter_username: mhdali
github_username:  mhdali

# Build settings
markdown: kramdown
markdown: redcarpet
